# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dcfe67d6bf528da34f6d94f750ed8bc1d89894e6b2dd39a5b3b52ebd204a5394bbe431079c73ad6c3e60f3bdf7d9e4c3f5cd25d3322d4effbd45a0f078d06013

test:
  secret_key_base: 38b00b58c5270504427d3d4e1b67448263ac54d31896ca40472f37f50f3cc57b6d0eb4a01cb5679e580a00d00f71094f51c881e4fe69838a41be33137d826619

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
